"""add_request_hash_to_idempotency_keys

Revision ID: 33cf03689587
Revises: a004a8b0dbbe
Create Date: 2026-07-03 08:39:05.170497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33cf03689587'
down_revision: Union[str, Sequence[str], None] = 'a004a8b0dbbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idempotency_keys', sa.Column('request_hash', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idempotency_keys', 'request_hash')
    # ### end Alembic commands ###
