"""create_initial_schema

Revision ID: a004a8b0dbbe
Revises: 
Create Date: 2026-07-03 08:22:09.264594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a004a8b0dbbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('player_id', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('idx_idempotency_keys_created_at', 'idempotency_keys', ['created_at'], unique=False)
    op.create_table('wallets',
    sa.Column('player_id', sa.String(length=128), nullable=False),
    sa.Column('balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance >= 0', name='chk_wallet_balance_non_negative'),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('claimed_rewards',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(length=128), nullable=False),
    sa.Column('reward_id', sa.String(length=128), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['wallets.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'reward_id', name='uq_player_reward')
    )
    op.create_index('idx_claimed_rewards_player_id', 'claimed_rewards', ['player_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(length=128), nullable=False),
    sa.Column('item_id', sa.String(length=128), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['wallets.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventory_player_id', 'inventory', ['player_id'], unique=False)
    op.create_table('ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=256), server_default='', nullable=False),
    sa.Column('reference_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance_after >= 0', name='chk_ledger_balance_after_non_negative'),
    sa.ForeignKeyConstraint(['player_id'], ['wallets.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_player_id', 'ledger', ['player_id'], unique=False)
    op.create_index('idx_ledger_reference_id', 'ledger', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ledger_reference_id', table_name='ledger')
    op.drop_index('idx_ledger_player_id', table_name='ledger')
    op.drop_table('ledger')
    op.drop_index('idx_inventory_player_id', table_name='inventory')
    op.drop_table('inventory')
    op.drop_index('idx_claimed_rewards_player_id', table_name='claimed_rewards')
    op.drop_table('claimed_rewards')
    op.drop_table('wallets')
    op.drop_index('idx_idempotency_keys_created_at', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
